import { cn } from '@mono/util';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getTimeZone } from 'next-intl/server';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import { availableLocalesMap, defaultLocale } from '../../../i18n/locales';
import { Providers } from '../../components/Providers';
import SessionProvider from '../../components/auth/SessionProvider';
import { getAuthSession } from '../../config/auth';
import '../../global.css';

export const metadata = {
  title: 'Welcome to store',
  description: 'Generated by alger',
};

const inter = Inter({ subsets: ['latin'] });

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const [messages, timezone, session] = await Promise.all([
    getMessages(),
    getTimeZone(),
    getAuthSession(),
  ]);

  const { langDir, hrefLang } = availableLocalesMap[locale] || defaultLocale;
  return (
    <html
      lang={hrefLang}
      dir={langDir}
      className="h-full"
      suppressHydrationWarning
    >
      <body
        className={cn(
          'text-foreground bg-background h-full font-sans antialiased',
          inter.className,
        )}
      >
        <Providers>
          <NextIntlClientProvider messages={messages} timeZone={timezone}>
            <SessionProvider session={session}>
              {children}
              <Toaster richColors closeButton position="top-right" />
            </SessionProvider>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
