import { Providers } from '@mono/ui';
import { cn } from '@mono/util';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider, useMessages, useTimeZone } from 'next-intl';
import AppProvider from '../../contexts/appContext';
import './global.css';
import { availableLocalesMap, defaultLocale } from '../../../i18n/locales';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by alger',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  const timezone = useTimeZone();
  const { langDir, hrefLang } = availableLocalesMap[locale] || defaultLocale;
  return (
    <html lang={hrefLang} dir={langDir}>
      <body className={cn('font-sans antialiased', inter.className)}>
        <Providers>
          <NextIntlClientProvider messages={messages} timeZone={timezone}>
            <AppProvider>{children}</AppProvider>
            <Toaster richColors closeButton position="top-right" />
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
