import './global.css';
import { Providers } from '@mono/ui';
import { cn } from '@mono/util';
import { Inter } from 'next/font/google';
// import { getServerSession } from 'next-auth';
// import { SessionProvider } from '@mono/ui';
import AppProvider from '../../contexts/appContext';
import { NextIntlClientProvider, useMessages } from 'next-intl';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // const session = await getServerSession();
  const messages = useMessages();
  return (
    <html lang={locale} dir={'ltr'}>
      <body className={cn('font-sans antialiased', inter.className)}>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            <AppProvider>{children}</AppProvider>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
